#!/bin/bash

echo "========================================"
echo " Настройка GitHub Pages для БелыйОбходчик"
echo "========================================"
echo ""

echo "1. Создайте репозиторий на GitHub:"
echo "   - Откройте https://github.com"
echo "   - Нажмите 'New repository'"
echo "   - Назовите: beliy-obhodchik"
echo "   - Описание: 'Автоматическая настройка интернета на Keenetic'"
echo "   - Public repository"
echo "   - Не добавляйте файлы (оставьте пустым)"
echo "   - Нажмите 'Create repository'"
echo ""
read -p "Нажмите Enter, когда создадите репозиторий..."

echo ""
echo "2. Загрузите файлы через браузер:"
echo "   - На странице репозитория нажмите 'Add file' -> 'Upload files'"
echo "   - Перетащите все файлы из этой папки:"
echo "     • landing_index.html"
echo "     • README.md"
echo "     • requirements.txt"
echo "     • *.py файлы"
echo "     • *.sql файлы"
echo "   - Нажмите 'Commit changes'"
echo ""
read -p "Нажмите Enter, когда загрузите файлы..."

echo ""
echo "3. Включите GitHub Pages:"
echo "   - На странице репозитория: Settings -> Pages"
echo "   - Branch: main"
echo "   - Folder: / (root)"
echo "   - Нажмите Save"
echo "   - Подождите 1-2 минуты"
echo ""
read -p "Нажмите Enter, когда включите GitHub Pages..."

echo ""
echo "4. Получите ссылку на сайт:"
echo "   - Вернитесь в Settings -> Pages"
echo "   - Скопируйте ссылку вида:"
echo "     https://ваш-логин.github.io/beliy-obhodchik/"
echo ""
read -p "Нажмите Enter, чтобы продолжить..."

echo ""
echo "========================================"
echo " Дополнительные шаги:"
echo "========================================"
echo ""

echo "A. Создание Telegram-бота:"
echo "   1. Откройте @BotFather в Telegram"
echo "   2. Команда: /newbot"
echo "   3. Имя: БелыйОбходчик"
echo "   4. Username: beliy_obhodchik_bot"
echo "   5. Скопируйте токен"
echo ""
read -p "Нажмите Enter для продолжения..."

echo ""
echo "B. Установка зависимостей и запуск бота:"
echo "   pip install pyTelegramBotAPI"
echo "   export TELEGRAM_BOT_TOKEN='ваш_токен'"
echo "   python telegram_bot.py"
echo ""
read -p "Нажмите Enter для завершения..."

echo ""
echo "========================================"
echo " Готово! Система запущена."
echo " Сайт: https://ваш-логин.github.io/beliy-obhodchik/"
echo " Бот: @beliy_obhodchik_bot"
echo "========================================"